// Leave this empty when the UI is served by the API (the production setup).
// Set window.SYNCTASK_API_URL before this file only when hosting the UI elsewhere.
const API = window.SYNCTASK_API_URL || '';
const state = { token: localStorage.getItem('synctask_token'), user: JSON.parse(localStorage.getItem('synctask_user') || 'null'), project: null, projects: [], taskPage: 0, taskPageCount: 0 };
const $ = s => document.querySelector(s);
const esc = value => { const el = document.createElement('span'); el.textContent = value || ''; return el.innerHTML; };
async function api(path, options = {}) { const headers = { ...(options.body ? {'Content-Type':'application/json'} : {}), ...(state.token ? {Authorization:`Bearer ${state.token}`} : {}) }; const res = await fetch(API + path, {...options, headers}); if (res.status === 401) { logout(); throw Error('Please sign in again.'); } if (!res.ok) { const body = await res.json().catch(() => ({})); throw Error(body.message || `Request failed (${res.status})`); } return res.status === 204 ? null : res.json(); }
function toast(message) { const t = $('#toast'); t.textContent = message; t.classList.add('show'); setTimeout(() => t.classList.remove('show'), 3000); }
function logout() { localStorage.removeItem('synctask_token'); localStorage.removeItem('synctask_user'); state.token = null; state.user = null; $('#dashboard').hidden = true; $('#auth').hidden = false; $('#who').hidden = true; showChoice(); }
function showChoice() { $('#choice').hidden = false; $('#form-page').hidden = true; }
function showForm(mode) { $('#choice').hidden = true; $('#form-page').hidden = false; $('#login').hidden = mode !== 'login'; $('#register').hidden = mode !== 'register'; $('#form-title').textContent = mode === 'login' ? 'Sign in' : 'Create your account'; $('#form-copy').textContent = mode === 'login' ? 'Enter your details to continue to your workspace.' : 'Once created, you will enter your workspace.'; }
function enterApp(auth) { state.token = auth.token; state.user = auth; localStorage.setItem('synctask_token', auth.token); localStorage.setItem('synctask_user', JSON.stringify(auth)); $('#auth').hidden = true; $('#dashboard').hidden = false; $('#who').hidden = false; $('#person').textContent = auth.name; loadProjects(); }
async function authenticate(event, path) { event.preventDefault(); try { const auth = await api(path, {method:'POST', body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))}); enterApp(auth); toast(path.endsWith('register') ? 'Account created. Welcome to your workspace.' : 'Signed in successfully.'); } catch (e) { toast(e.message); } }
async function loadProjects() { try { const data = await api('/api/projects?size=100'); state.projects = data.content || []; const box = $('#projects'); box.innerHTML = state.projects.length ? '' : '<small>No projects yet.</small>'; state.projects.forEach(p => { const b = document.createElement('button'); b.className = `project${state.project?.id === p.id ? ' active':''}`; b.innerHTML = `<strong>${esc(p.name)}</strong><small>${esc(p.description || 'No description')}</small>`; b.onclick = () => selectProject(p.id); box.append(b); }); } catch (e) { toast(e.message); } }
async function selectProject(id) { try { state.project = await api(`/api/projects/${id}`); state.taskPage = 0; $('#empty').hidden = true; $('#project-panel').hidden = false; $('#project-name').textContent = state.project.name; $('#project-description').textContent = state.project.description || 'No description'; renderMembers(); await loadProjects(); loadTasks(); } catch (e) { toast(e.message); } }
function isElevated() { return state.user && (state.user.role === 'ADMIN' || state.user.role === 'MANAGER'); }
function renderMembers() { const box = $('#members'); box.innerHTML = ''; const canManage = isElevated(); $('#add-member').hidden = !canManage; (state.project.members || []).forEach(m => { const pill = document.createElement('span'); pill.className = 'member-pill'; const isCreator = state.project.createdBy?.id === m.id; pill.innerHTML = `<span>${esc(m.name)} <small>${esc(m.role)}</small></span>`; if (canManage && !isCreator) { const btn = document.createElement('button'); btn.type = 'button'; btn.textContent = '×'; btn.title = `Remove ${m.name}`; btn.onclick = () => removeMember(m.id); pill.append(btn); } box.append(pill); }); }
async function removeMember(userId) { try { await api(`/api/projects/${state.project.id}/members/${userId}`, {method:'DELETE'}); toast('Member removed.'); await selectProject(state.project.id); } catch (e) { toast(e.message); } }
async function loadTasks() { if (!state.project) return; try { const params = new URLSearchParams({ page: state.taskPage, size: 5, sort: $('#sort').value }); if ($('#filter').value) params.set('status', $('#filter').value); const data = await api(`/api/projects/${state.project.id}/tasks?${params}`); const box = $('#tasks'); box.innerHTML = data.content.length ? '' : '<div class="empty"><h2>No tasks yet</h2><p>Add the first task to begin.</p></div>'; data.content.forEach(t => { const own = t.assignedTo?.id === state.user.userId; const card = document.createElement('div'); card.className = 'task'; card.innerHTML = `<div><h3>${esc(t.title)}</h3><p>${esc(t.description || 'No description')}</p><small>${t.status.replace('_',' ')} · ${t.dueDate || 'No due date'}</small></div><select ${own ? '' : 'disabled'}><option value="TODO">To do</option><option value="IN_PROGRESS">In progress</option><option value="DONE">Done</option></select>`; const sel = card.querySelector('select'); sel.value = t.status; sel.onchange = () => updateStatus(t.id, sel.value); box.append(card); }); state.taskPage = data.number; state.taskPageCount = data.totalPages; const pagination = $('#pagination'); pagination.hidden = data.totalPages <= 1; $('#page-info').textContent = `Page ${data.number + 1} of ${data.totalPages}`; $('#previous-page').disabled = data.first; $('#next-page').disabled = data.last; } catch (e) { toast(e.message); } }
async function updateStatus(id,status) { try { await api(`/api/projects/${state.project.id}/tasks/${id}/status`, {method:'PATCH',body:JSON.stringify({status})}); toast('Task updated.'); loadTasks(); } catch(e) { toast(e.message); loadTasks(); } }
$('#login').onsubmit = e => authenticate(e, '/api/auth/login'); $('#register').onsubmit = e => authenticate(e, '/api/auth/register'); document.querySelectorAll('[data-mode]').forEach(b => b.onclick = () => showForm(b.dataset.mode)); $('#back').onclick = showChoice; $('#logout').onclick = logout; $('#filter').onchange = () => { state.taskPage = 0; loadTasks(); }; $('#sort').onchange = () => { state.taskPage = 0; loadTasks(); }; $('#previous-page').onclick = () => { if (state.taskPage > 0) { state.taskPage--; loadTasks(); } }; $('#next-page').onclick = () => { if (state.taskPage + 1 < state.taskPageCount) { state.taskPage++; loadTasks(); } }; $('#refresh').onclick = loadTasks; document.querySelectorAll('[data-close]').forEach(button => button.onclick = () => { const dialog = $(`#${button.dataset.close}`); dialog.close(); dialog.querySelector('form').reset(); });
$('#new-project').onclick = () => $('#project-dialog').showModal(); $('#project-form').onsubmit = async e => { e.preventDefault(); try { const p = await api('/api/projects',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))}); e.target.reset(); $('#project-dialog').close(); toast('Project created.'); await selectProject(p.id); } catch(err) { toast(err.message); } };
$('#new-task').onclick = () => $('#task-dialog').showModal(); $('#task-form').onsubmit = async e => { e.preventDefault(); try { const data = Object.fromEntries(new FormData(e.target)); data.assignedToId = state.user.userId; if (!data.dueDate) data.dueDate = null; await api(`/api/projects/${state.project.id}/tasks`, {method:'POST',body:JSON.stringify(data)}); e.target.reset(); $('#task-dialog').close(); toast('Task created.'); loadTasks(); } catch(err) { toast(err.message); } };
$('#add-member').onclick = () => $('#member-dialog').showModal(); $('#member-form').onsubmit = async e => { e.preventDefault(); try { const data = Object.fromEntries(new FormData(e.target)); await api(`/api/projects/${state.project.id}/members`, {method:'POST',body:JSON.stringify({userId:Number(data.userId)})}); e.target.reset(); $('#member-dialog').close(); toast('Member added.'); await selectProject(state.project.id); } catch(err) { toast(err.message); } };
state.token && state.user ? enterApp(state.user) : showChoice();
